services:
  web:
    build: .
    container_name: setup-demo-web
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: setup-demo-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: